name: mushroom-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - opencv
  - numpy
  - tqdm
  - pip:
    - albumentations==1.3.1
    - opencv-python-headless==4.9.0.80
