name: mushroom
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - cpuonly  # 确保使用CPU版本
  - pip
  - pip:
      - ultralytics
      - opencv-python
      - numpy