name: mushroom-env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - python=3.8
  - pip
  - opencv
  - numpy
  - tqdm
  - pip:
    - albumentations==1.3.1
    - opencv-python-headless==4.9.0.80
